---
# TravisCI config info: https://docs.codeclimate.com/docs/travis-ci-test-coverage
env:
  global:
    - CC_TEST_REPORTER_ID=304a38cb2ff3b8a793c4079709b23fd514812a8bbf694cb290a3afe31cf8f04a
language: ruby
bundler_args: --with ci
cache: bundler
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: bundle exec rake spec_ci
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
rvm:
  - 2.7
  - 2.6
  - 2.5
before_install: gem install bundler -v 1.17.3
